# server??
server:
  port: 8080
  servlet:
    context-path: /

# mysql config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/nmb_map
      username: root
      password: lx2310282802
      driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB # single file size limit
      max-request-size: 20MB # multiple file size limit

# mybatis-plus config
mybatis-plus:
  type-handlers-package: com.baomidou.mybatisplus.extension.handlers
  type-aliases-package: com.swe.nmb_map.entity
  global-config:
    db-config:
      logic-delete-field: isDeleted  # logical delete
      id-type: auto

#jwt??
jwt:
  token:
    tokenExpiration: 120 # two hours
    tokenSignKey: nmb_map123456  # sign key

wx:
  appid: wx779e1909e689a563
  secret: 0c44946ccebda3da66cc9adaa543c852