# server??
server:
  port: 8080
  servlet:
    context-path: /

# ?????
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/nmb_map
      username: root
      password: lx2310282802
      driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis-plus???
mybatis-plus:
  type-handlers-package: com.baomidou.mybatisplus.extension.handlers
  type-aliases-package: com.swe.nmb_map.entity
  global-config:
    db-config:
      logic-delete-field: isDeleted  #??????
      id-type: auto #???????

#jwt??
jwt:
  token:
    tokenExpiration: 120 #????,????
    tokenSignKey: nmb_map123456  #???????? ???